modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
license="GNU LESSER GENERAL PUBLIC LICENSE"
logoBlur=false


[[mods]] #mandatory
modId="customclient" #mandatory
version="1.0" #mandatory
displayName="CustomClient" #mandatory
authors="land" #optional
description="Customclient"
displayURL=""

[[dependencies.customclient]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[20.5,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.customclient]]
modId="minecraft"
type="required"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"

